### ISSUE TITLE
Bug : SPIF_WriteAddress()

### ISSUE THREAD

**Issue by EdouardMALOT** [nimaltd/spif#44]
Thank you for sharing your project.

I found a bug using SPIF_WriteAddress() with the address not aligned to SPIF_PAGE_SIZE.

The problem is that "remaining" is compared to SPIF_PAGE_SIZE instead of ( SPIF_PAGE_SIZE - offset).

The corrected code looks like this 
<img width="806" alt="image" src="https://github.com/nimaltd/spif/assets/11795982/d4705cc9-0bcc-4dfd-b9c1-a4cccb2a6e3e">

**Comment by nimaltd** [comment]
hello. thanks for your correction. but as I can remember, checking the offset is in the SPIF_WriteFn function. please have look and tel me your opinion. thanks

**Comment by EdouardMALOT** [comment]
Yes SPIF_WriteFn() limit "Size" but does it _**silently**_ :  

<img width="954" alt="image" src="https://github.com/nimaltd/spif/assets/11795982/411d5a6c-c4d4-4a6b-b611-ea06bef67fe7">

This is why I applied the **same limit** with the same "maximum" variable name **in SPIF_WriteAddress()**.
(Otherwise not all data is written and there are no errors reported).

**Comment by nimaltd** [comment]
it has been updated. please have a look. thanks
