### ISSUE TITLE
Offset value not being used in READ functions

### ISSUE THREAD

**Issue by paul-thelu** [nimaltd/spif#47]
Hello,

I struggled reading the flash memory after writing in it using LittleFS, and led me to go through the SPIF functions.
I noted the Offset value in argument of all the READ functions was absent.

https://github.com/nimaltd/spif/blob/cd79138e700a2e794dfb6ca5a70020a17d74905b/spif.c#L1269

Should not it be something like:
uint32_t address = SPIF_SectorToAddress(SectorNumber) + **Offset**;
Instead of:
uint32_t address = SPIF_SectorToAddress(SectorNumber);

After some further testings this solved my issue but I need further testings to be 100% sure.
If anyone else could confirm I would appreciate so we could possibly fix this issue.

Thank you for this library as it has great potential to be used together with LittleFS as it covers many Flash memory manufacturers.

Paul

**Comment by nimaltd** [comment]
Hello. oh yes. my bad :)
i will fix it.
