### ISSUE TITLE
Wrong ISSI device address

### ISSUE THREAD

**Issue by paul-thelu** [nimaltd/spif#48]
Hello,

I noted a typo in spif.h here:
https://github.com/nimaltd/spif/blob/cd79138e700a2e794dfb6ca5a70020a17d74905b/spif.h#L87

The device address should be 0x9D for the ISSI range of NOR flash memories, as per the datasheet below (page 59):
https://www.issi.com/WW/pdf/IS25LP128.pdf

Many thanks for the library,

Paul

**Comment by nimaltd** [comment]
thanks. i will solve it
