### ISSUE TITLE
32kb write on flash

### ISSUE THREAD

**Issue by Hrishie89** [nimaltd/spif#50]
I want to write 32kb of data in one go; how can i do that ???

**Comment by nimaltd** [comment]
Write sector

**Comment by Hrishie89** [comment]
uint8_t testwrite[32768]={0};
uint8_t testRead[32768]={0};
SPIF_HandleTypeDef spif;
  for (int i = 0; i < 32768; i++)
    {
      testwrite[i] = i + 16;
    }

  SPIF_EraseBlock(&spif, 0);
  SPIF_WriteBlock(&spif, 0, testwrite, 4096, 0);
  SPIF_ReadBlock(&spif, 0, testRead, 4096, 0);

like this ?

**Comment by nimaltd** [comment]
It seems correct
